week_4_project/views/answer_views.py
from flask import Blueprint, url_for, render_template, redirect, abort, flash, request, g
from datetime import datetime
from week_4_project.forms import AnswerForm
import week_4_project.models as models
from .auth_views import login_required

bp = Blueprint('answer', __name__, url_prefix='/answer')

@bp.route('/create/<int:question_id>/', methods=('POST',))
@login_required
def create(question_id):
    form = AnswerForm()
    question = models.get_question_by_id(question_id)
    if question is None:
        abort(404)
    
    if form.validate_on_submit():
        content = form.content.data
        models.insert_answer(question_id, content, g.user['id'])
        return redirect(url_for('question.q_detail', question_id=question_id))
    
    answers = models.get_answers_by_question_id(question_id)
    return render_template('question/question_detail.html', question=question, answers=answers, form=form)

@bp.route('/modify/<int:answer_id>/', methods=('GET', 'POST'))
@login_required
def modify(answer_id):
    answer = models.get_answer_by_id(answer_id)
    if answer is None or g.user['id'] != answer['user_id']:
        flash('수정권한이 없습니다')
        return redirect(url_for('question.q_detail', question_id=answer['question_id']))
    if request.method == 'POST':
        form = AnswerForm()
        if form.validate_on_submit():
            models.update_answer(answer_id, form.content.data)
            return redirect(url_for('question.q_detail', question_id=answer['question_id']))
    else:
        form = AnswerForm(data={'content': answer['content']})
    return render_template('answer/answer_form.html', form=form)

@bp.route('/delete/<int:answer_id>/')
@login_required
def delete(answer_id):
    answer = models.get_answer_by_id(answer_id)
    if answer is None:
        abort(404)
    question_id = answer['question_id']
    if g.user['id'] != answer['user_id']:
        flash('삭제권한이 없습니다')
    else:
        models.delete_answer(answer_id)
    return redirect(url_for('question.q_detail', question_id=question_id))

week_4_project/views/auth_views.py
from flask import Blueprint, url_for, render_template, flash, abort, request, session, g, current_app
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect
import week_4_project.models as models
from week_4_project.forms import UserCreateForm, UserLoginForm, ProfileForm, FindUsernameForm, ResetPasswordRequestForm, ResetPasswordForm
import functools
import os
import uuid
from flask_mail import Mail, Message
from itsdangerous import URLSafeTimedSerializer, SignatureExpired

bp = Blueprint('auth', __name__, url_prefix='/auth')
mail = Mail()

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(*args, **kwargs):
        if g.user is None:
            _next = request.url if request.method == 'GET' else ''
            return redirect(url_for('auth.signin', next=_next))
        return view(*args, **kwargs)
    return wrapped_view

@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = models.get_user_by_id(user_id)

@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.index'))

@bp.route('/signup/', methods=('GET', 'POST'))
def signup():
    form = UserCreateForm()
    if request.method == 'POST' and form.validate_on_submit():
        user = models.get_user_by_username(form.username.data)
        email = models.get_user_by_email(form.email.data)
        if not user and not email:
            hashed_password = generate_password_hash(form.password1.data)
            models.insert_user(form.username.data, hashed_password, form.email.data, form.name.data, form.school.data)
            return redirect(url_for('main.index'))
        else:
            flash('이미 존재하는 사용자 이름 또는 이메일입니다.')
    return render_template('auth/signup.html', form=form)

@bp.route('/signin/', methods=('GET', 'POST'))
def signin():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = models.get_user_by_username(form.username.data)
        if not user:
            error = "존재하지 않는 사용자입니다."
        elif not check_password_hash(user['password'], form.password.data):
            error = "비밀번호가 올바르지 않습니다."
        if error is None:
            session.clear()
            session['user_id'] = user['id']
            _next = request.args.get('next', '')
            if _next:
                return redirect(_next)
            else:
                return redirect(url_for('main.index'))
        flash(error)
    return render_template('auth/signin.html', form=form)

def allowed_profile_image(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in current_app.config['PROFILE_IMAGE_ALLOWED_EXTENSIONS']

@bp.route('/profile/', methods=('GET', 'POST'))
@login_required
def profile():
    form = ProfileForm()
    if request.method == 'POST' and form.validate_on_submit():
        name = form.name.data
        school = form.school.data
        profile_image = form.profile_image.data
        if profile_image and allowed_profile_image(profile_image.filename):
            # 기존 프로필 이미지 삭제
            if g.user['profile_image']:
                existing_image_path = os.path.join(current_app.config['UPLOAD_FOLDER'], g.user['profile_image'])
                if os.path.exists(existing_image_path):
                    os.remove(existing_image_path)
            
            file_ext = profile_image.filename.split('.')[-1]
            profile_image_filename = f"{g.user['id']}_{uuid.uuid4().hex}.{file_ext}"
            profile_image.save(os.path.join(current_app.config['UPLOAD_FOLDER'], profile_image_filename))
            g.user['profile_image'] = profile_image_filename
        models.update_user_profile(g.user['id'], name, school, g.user['profile_image'])
        flash('프로필이 업데이트되었습니다.')
        return redirect(url_for('auth.profile'))
    return render_template('profile.html', form=form, user=g.user, editable=True)

@bp.route('/profile/<int:user_id>/', methods=('GET',))
@login_required
def view_profile(user_id):
    user = models.get_user_by_id(user_id)
    if user is None:
        abort(404)
    form = ProfileForm(obj=user)
    return render_template('profile.html', form=form, user=user, editable=False)

def generate_reset_token(email):
    serializer = URLSafeTimedSerializer(current_app.config['SECRET_KEY'])
    return serializer.dumps(email, salt=current_app.config['SECURITY_PASSWORD_SALT'])

@bp.route('/reset_password_request/', methods=['GET', 'POST'])
def reset_password_request():
    form = ResetPasswordRequestForm()
    if form.validate_on_submit():
        email = form.email.data
        user = models.get_user_by_email(email)
        if user:
            token = generate_reset_token(email)
            reset_url = url_for('auth.reset_password', token=token, _external=True)
            msg = Message('비밀번호 재설정', sender=current_app.config['MAIL_USERNAME'], recipients=[email])
            msg.body = f"비밀번호 재설정 링크: {reset_url}"
            mail.send(msg)
            flash('비밀번호 재설정 메일이 전송 되었습니다.', 'info')
        else:
            flash('등록된 이메일이 아닙니다.', 'danger')
        return redirect(url_for('auth.reset_password_request'))
    return render_template('auth/reset_password_request.html', form=form)

def confirm_reset_token(token, expiration=3600):
    serializer = URLSafeTimedSerializer(current_app.config['SECRET_KEY'])
    try:
        email = serializer.loads(token, salt=current_app.config['SECURITY_PASSWORD_SALT'], max_age=expiration)
    except SignatureExpired:
        return False
    return email

@bp.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    try:
        email = confirm_reset_token(token)
    except:
        flash('재설정 링크가 잘못되었거나 만료되었습니다.', 'danger')
        return redirect(url_for('auth.reset_password_request'))

    form = ResetPasswordForm()
    if form.validate_on_submit():
        password = form.password.data
        hashed_password = generate_password_hash(password)
        models.update_user_password(email, hashed_password)
        flash('비밀번호가 업데이트 되었습니다.', 'success')
        return redirect(url_for('auth.signin'))
    return render_template('auth/reset_password.html', form=form)

@bp.route('/find_username/', methods=['GET', 'POST'])
def find_username():
    form = FindUsernameForm()
    if form.validate_on_submit():
        email = form.email.data
        user = models.get_user_by_email(email)
        if user:
            flash(f"사용자 ID: {user['username']}", 'info')
        else:
            flash('등록된 이메일이 아닙니다.', 'danger')
        return redirect(url_for('auth.find_username'))
    return render_template('auth/find_username.html', form=form)

week_4_project/views/question_views.py
from flask import Blueprint, render_template, request, url_for, g, flash, redirect, abort, current_app, send_from_directory
from week_4_project.forms import QuestionForm, AnswerForm
from week_4_project.views.auth_views import login_required
from werkzeug.security import generate_password_hash, check_password_hash
import week_4_project.models as models
import os
import uuid

bp = Blueprint('question', __name__, url_prefix='/question')

@bp.route('/list/')
def q_list():
    page = request.args.get('page', type=int, default=1)
    kw = request.args.get('kw', type=str, default='')
    per_page = 2
    offset = (page - 1) * per_page

    question_list = models.get_paginated_questions(offset, per_page)
    if kw:
        question_list = models.search_questions(kw, offset, per_page)

    total_questions = models.get_question_count()
    total_pages = (total_questions + per_page - 1) // per_page
    return render_template('question/question_list.html', question_list=question_list, page=page, kw=kw, total_pages=total_pages, per_page=per_page)

def allowed_question_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in current_app.config['QUESTION_FILE_ALLOWED_EXTENSIONS']

@bp.route('/create/', methods=('GET', 'POST'))
@login_required
def q_create():
    form = QuestionForm()
    if request.method == 'POST' and form.validate_on_submit():
        password = form.password.data
        if password:
            password = generate_password_hash(password)
        
        file_path = None
        file = form.file.data
        if file and allowed_question_file(file.filename):
            file_ext = file.filename.split('.')[-1]
            file_path = f"{g.user['id']}_{uuid.uuid4().hex}.{file_ext}"
            file.save(os.path.join(current_app.config['QUESTION_FILE_UPLOAD_FOLDER'], file_path))
        
        models.insert_question(form.title.data, form.content.data, g.user['id'], password, file_path)
        return redirect(url_for('question.q_list'))
    return render_template('question/question_form.html', form=form)

@bp.route('/download/<filename>')
def download_file(filename):
    return send_from_directory(current_app.config['QUESTION_FILE_UPLOAD_FOLDER'], filename, as_attachment=True)

@bp.route('/detail/<int:question_id>/', methods=('GET', 'POST'))
def q_detail(question_id):
    question = models.get_question_by_id(question_id)
    if question is None:
        abort(404)
    if question['password']:
        if request.method == 'POST':
            password = request.form['password']
            if not check_password_hash(question['password'], password):
                flash('비밀번호가 틀렸습니다.')
                return redirect(url_for('question.q_detail', question_id=question_id))
        else:
            return render_template('question/question_password.html', question_id=question_id)
    answers = models.get_answers_by_question_id(question_id)
    form = AnswerForm()
    return render_template('question/question_detail.html', question=question, answers=answers, form=form)

@bp.route('/modify/<int:question_id>/', methods=('GET', 'POST'))
@login_required
def modify(question_id):
    question = models.get_question_by_id(question_id)
    if question is None or g.user['id'] != question['user_id']:
        flash('수정권한이 없습니다')
        return redirect(url_for('question.q_detail', question_id=question_id))
    if request.method == 'POST':
        form = QuestionForm()
        if form.validate_on_submit():
            models.update_question(question_id, form.title.data, form.content.data)
            return redirect(url_for('question.q_detail', question_id=question_id))
    else:
        form = QuestionForm(data={'title': question['title'], 'content': question['content']})
    return render_template('question/question_form.html', form=form)

@bp.route('/delete/<int:question_id>/')
@login_required
def delete(question_id):
    question = models.get_question_by_id(question_id)
    if question is None or g.user['id'] != question['user_id']:
        flash('삭제권한이 없습니다')
        return redirect(url_for('question.q_detail', question_id=question_id))
    models.delete_question(question_id)
    return redirect(url_for('question.q_list'))

week_4_project/templates/question/question_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-danger" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    <h2 class="border-bottom py-2">{{ question.title }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            {% if question.file_path %}
            <div class="mt-3">
                <a href="{{ url_for('question.download_file', filename=question.file_path) }}" class="btn btn-outline-primary">파일 다운로드</a>
            </div>
            {% endif %}
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ question.username }}</div>
                    <div>{{ question.time }}</div>
                </div>
            </div>
            <div class="my-3">
                {% if g.user['id'] == question.user_id %}
                <a href="{{ url_for('question.modify', question_id=question.id) }}" class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary" data-uri="{{ url_for('question.delete', question_id=question.id) }}">삭제</a>
                {% endif %}
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{ answers|length }}개의 답변이 있습니다.</h5>
    {% for answer in answers %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ answer.username }}</div>
                    <div>{{ answer.time }}</div>
                </div>
            </div>
            <div class="my-3">
                {% if g.user['id'] == answer.user_id %}
                <a href="{{ url_for('answer.modify', answer_id=answer.id) }}" class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="#" class="delete btn btn-sm btn-outline-secondary " data-uri="{{ url_for('answer.delete', answer_id=answer.id) }}">삭제</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{{ url_for('answer.create', question_id=question.id) }}" method="post" class="my-3">
        {{ form.csrf_token }}
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field, errors in form.errors.items() %}
            <strong>{{ form[field].label }}</strong>
            <ul>
                {% for error in errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
            {% endfor %}
        </div>
        {% endif %}
        <div class="mb-3">
            <textarea {% if not g.user %}disabled{% endif %} name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}

{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}

week_4_project/templates/question/question_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post" enctype="multipart/form-data" class="my-3">
        {{ form.csrf_token }}
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field, errors in form.errors.items() %}
            <strong>{{ form[field].label }}</strong>
            <ul>
                {% for error in errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
            {% endfor %}
        </div>
        {% endif %}
        <div class="mb-3">
            <label for="title">제목</label>
            <input type="text" class="form-control" name="title" id="title" value="{{ form.title.data or '' }}">
        </div>
        <div class="mb-3">
            <label for="content">내용</label>
            <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.data or '' }}</textarea>
        </div>
        <div class="mb-3">
            <label for="password">비밀번호 (선택사항)</label>
            <input type="password" class="form-control" name="password" id="password" value="{{ form.password.data or '' }}">
        </div>
        <div class="mb-3">
            <label for="file">파일 업로드</label>
            <input type="file" class="form-control" name="file" id="file">
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

week_4_project/templates/question/question_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-6">
            <a href="{{ url_for('question.q_create') }}" class="btn btn-primary">질문 등록하기</a>
        </div>
        <div class="col-6">
            <div class="input-group">
                <input type="text" id="search_kw" class="form-control" value="{{ kw or '' }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                </div>
            </div>
        </div>
    </div>
    <table class="table">
        <thead>
        <tr class="text-center table-dark">
            <th>번호</th>
            <th style="width:50%">제목</th>
            <th>글쓴이</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr class="text-center">
            <td>{{ loop.index + (page - 1) * per_page }}</td>
            <td class="text-start">
                <a href="{{ url_for('question.q_detail', question_id=question.id) }}">{{ question.title }}</a>
                {% if question.answer_count > 0 %}
                <span class="text-danger small mx-2">{{ question.answer_count }}</span>
                {% endif %}
                {% if question.password %}
                <span class="text-warning mx-2">🔒</span>
                {% endif %}
            </td>
            <td><a href="{{ url_for('auth.view_profile', user_id=question.user_id) }}">{{ question.username }}</a></td>
            <td>{{ question.time }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="4">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>

    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            <!-- 이전 페이지 -->
            {% if page > 1 %}
            <li class="page-item">
                <a class="page-link" data-page="{{ page-1 }}" href="javascript:void(0)">이전</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">이전</a>
            </li>
            {% endif %}

            <!-- 페이지 번호 -->
            {% for p in range(1, total_pages + 1) %}
            {% if p == page %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" data-page="{{ p }}" href="javascript:void(0)">{{ p }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" data-page="{{ p }}" href="javascript:void(0)">{{ p }}</a>
            </li>
            {% endif %}
            {% endfor %}

            <!-- 다음 페이지 -->
            {% if page < total_pages %}
            <li class="page-item">
                <a class="page-link" data-page="{{ page+1 }}" href="javascript:void(0)">다음</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">다음</a>
            </li>
            {% endif %}
        </ul>
    </nav>
</div>
<form id="searchForm" method="get" action="{{ url_for('question.q_list') }}">
    <input type="hidden" id="kw" name="kw" value="{{ kw or '' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>

{% block script %}
<script type='text/javascript'>
const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('searchForm').submit();
    });
});
const btn_search = document.getElementById("btn_search");
btn_search.addEventListener('click', function() {
    document.getElementById('kw').value = document.getElementById('search_kw').value;
    document.getElementById('page').value = 1;
    document.getElementById('searchForm').submit();
});
</script>
{% endblock %}
{% endblock %}

week_4_project/templates/question/question_password.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">비밀번호 입력</h5>
    <form method="post">
        <div class="mb-3">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password" required>
        </div>
        <button type="submit" class="btn btn-primary">확인</button>
    </form>
</div>
{% endblock %}